package model

import (
	"testing"

	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
	"gorm.io/driver/sqlite"
	"gorm.io/gorm"
)

func setupUserTestDB(t *testing.T) *gorm.DB {
	t.Helper()
	db, err := gorm.Open(sqlite.Open(":memory:"), &gorm.Config{})
	require.NoError(t, err)
	require.NoError(t, db.AutoMigrate(&User{}))
	return db
}

func TestUser_BeforeCreate_GeneratesUUIDWhenIDIsEmpty(t *testing.T) {
	db := setupUserTestDB(t)

	user := &User{
		Email:    "test@example.com",
		Password: "hashedpassword",
		Nickname: "tester",
	}

	err := db.Create(user).Error
	require.NoError(t, err)

	assert.NotEmpty(t, user.ID, "ID should be generated by BeforeCreate hook")
	assert.Len(t, user.ID, 36, "generated ID should be a UUID (36 chars)")
}

func TestUser_BeforeCreate_PreservesExistingID(t *testing.T) {
	db := setupUserTestDB(t)

	existingID := "custom-id-1234-5678-abcd-ef0123456789"
	user := &User{
		ID:       existingID,
		Email:    "test2@example.com",
		Password: "hashedpassword",
		Nickname: "tester2",
	}

	err := db.Create(user).Error
	require.NoError(t, err)

	assert.Equal(t, existingID, user.ID, "BeforeCreate should not overwrite an existing ID")
}

func TestUser_BeforeCreate_GeneratesUniqueIDsForMultipleUsers(t *testing.T) {
	db := setupUserTestDB(t)

	user1 := &User{Email: "a@example.com", Password: "pass", Nickname: "aa"}
	user2 := &User{Email: "b@example.com", Password: "pass", Nickname: "bb"}

	require.NoError(t, db.Create(user1).Error)
	require.NoError(t, db.Create(user2).Error)

	assert.NotEqual(t, user1.ID, user2.ID, "each user should receive a unique UUID")
}

func TestUser_FieldPresence_UniqueEmailIsEnforced(t *testing.T) {
	db := setupUserTestDB(t)

	user1 := &User{Email: "same@example.com", Password: "pass", Nickname: "nick1"}
	user2 := &User{Email: "same@example.com", Password: "pass", Nickname: "nick2"}

	require.NoError(t, db.Create(user1).Error)
	err := db.Create(user2).Error
	assert.Error(t, err, "inserting a duplicate email should fail due to uniqueIndex")
}

func TestUser_FieldPresence_AllFieldsStoredAndRetrieved(t *testing.T) {
	db := setupUserTestDB(t)

	user := &User{
		Email:         "full@example.com",
		Password:      "secret",
		Nickname:      "fulluser",
		AvatarURL:     "https://example.com/avatar.png",
		StatusMessage: "Hello world",
	}
	require.NoError(t, db.Create(user).Error)

	var found User
	require.NoError(t, db.First(&found, "id = ?", user.ID).Error)

	assert.Equal(t, user.Email, found.Email)
	assert.Equal(t, user.Nickname, found.Nickname)
	assert.Equal(t, user.AvatarURL, found.AvatarURL)
	assert.Equal(t, user.StatusMessage, found.StatusMessage)
	assert.NotZero(t, found.CreatedAt)
	assert.NotZero(t, found.UpdatedAt)
}

func TestUser_SoftDelete_DoesNotHardDelete(t *testing.T) {
	db := setupUserTestDB(t)

	user := &User{
		Email:    "delete@example.com",
		Password: "pass",
		Nickname: "del",
	}
	require.NoError(t, db.Create(user).Error)
	require.NoError(t, db.Delete(user).Error)

	var found User
	err := db.First(&found, "id = ?", user.ID).Error
	assert.Error(t, err, "soft-deleted user should not appear in normal queries")

	var unscoped User
	err = db.Unscoped().First(&unscoped, "id = ?", user.ID).Error
	assert.NoError(t, err, "soft-deleted user should still exist in DB")
	assert.NotNil(t, unscoped.DeletedAt.Time)
}
